// <auto-generated />
using EmployeeCRUDApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace EmployeeCRUDApp.Data.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20220713140418_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeCRUDApp.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDRESSLINE1")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ADDRESSLINE2")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CITY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("COUNTRY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FIRSTNAME")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LASTNAME")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MOBILENUMBER")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID");

                    b.ToTable("EMPLOYEES");
                });
#pragma warning restore 612, 618
        }
    }
}
